name: home_resident
description: Aplicacion Movil Home Resident

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # flutter_svg: ^0.20.0-nullsafety.3
  flutter_svg: ^0.19.2+1
  after_layout: ^1.0.7+2
  cached_network_image: ^2.1.0+1
  image_picker: ^0.6.5+2
  shared_preferences: ^0.5.7+3
  shimmer: ^1.1.2
  websafe_svg: ^1.1.4+1
  get: ^3.26.0
  audioplayers: ^0.14.2
  intl: ^0.15.8
  connectivity: ^2.0.2
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/login.svg
    - assets/icons/mail.svg
    - assets/icons/user.svg
    - assets/icons/menu.svg
    - assets/icons/adjust.svg
    - assets/icons/history.svg
    - assets/icons/count.svg
    - assets/coronaVirus.jpg
    - assets/gmail.svg
    - assets/icons/back.svg
    - assets/icons/galery.svg
    - assets/icons/camera.svg
    - assets/icons/chats.svg
    - assets/icons/exit.svg
    - assets/icons/downArrow.svg
    - assets/icons/bell.png
    - assets/icons/Bell.svg
    - assets/icons/security.svg
    - assets/icons/rightArrow.svg
    - assets/default/thinking.png
    - assets/icons/bg.svg
    - assets/icons/clock.svg
    - assets/icons/fondo.png
    - assets/icons/imageNotAvailable.svg
    - assets/DefaultImage.png
    - assets/notAvailable.png
    - assets/asignaturas.png
    - assets/sound/correcto.mp3
    - assets/sound/error.mp3
    - assets/sound/finish.mp3
  #  - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
